ExpeNZes/urls.py
from django.contrib import admin
from django.urls import path
from apps.main.views import CuentaList, MovimientoFinancieroList, MovimientoFinancieroCreate, MovimientoFinancieroUpdate, MovimientoFinancieroDelete, IndexLogin, log_user_out, IndexLoginError, CuentaList, CuentaCreate, CuentaUpdate, CuentaDelete, CategoriaMovimientoFinancieroList, CategoriaMovimientoFinancieroCreate, CategoriaMovimientoFinancieroUpdate, CategoriaMovimientoFinancieroDelete #, validateLogin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexLogin.as_view(), name="indexLogin"),
    path('validateLogin/', IndexLogin.as_view(), name="validateLogin"),
    path('indexLoginError/',IndexLoginError.as_view(), name='indexLoginError'),
    path('logout/', log_user_out, name="logout"),
    path('listarMovimientosFinancieros/', MovimientoFinancieroList.as_view(), name='listarMovimientosFinancieros'),
    path('crearMovimientoFinanciero/', MovimientoFinancieroCreate.as_view(), name='crearMovimientoFinanciero'),
    path('actualizarMovimientoFinanciero/<int:pk>', MovimientoFinancieroUpdate.as_view(), name='actualizarMovimientoFinanciero'),
    path('eliminarMovimientoFinanciero/<int:pk>', MovimientoFinancieroDelete.as_view(), name='eliminarMovimientoFinanciero'),
    path('listarCuentas/', CuentaList.as_view(), name='listarCuentas'),
    path('crearCuenta/', CuentaCreate.as_view(), name='crearCuenta'),
    path('actualizarCuenta/<int:pk>', CuentaUpdate.as_view(), name='actualizarCuenta'),
    path('eliminarCuenta/<int:pk>', CuentaDelete.as_view(), name='eliminarCuenta'),
    path('listarCategoriasMovimientoFinanciero/', CategoriaMovimientoFinancieroList.as_view(), name='listarCategoriasMovimientoFinanciero'),
    path('crearCategoriaMovimientoFinanciero/', CategoriaMovimientoFinancieroCreate.as_view(), name='crearCategoriaMovimientoFinanciero'),
    path('actualizarCategoriaMovimientoFinanciero/<int:pk>', CategoriaMovimientoFinancieroUpdate.as_view(), name='actualizarCategoriaMovimientoFinanciero'),
    path('eliminarCategoriaMovimientoFinanciero/<int:pk>', CategoriaMovimientoFinancieroDelete.as_view(), name='eliminarCategoriaMovimientoFinanciero'),
]

apps/main/forms.py
from django import forms
from django.db.models import fields
from django.db.models.fields.mixins import FieldCacheMixin
from .models import MovimientoFinanciero, Cuenta, CategoriaMovimientoFinanciero

"""
class MovimientoFinancieroForm(forms.ModelForm):
    class Meta:
        model = MovimientoFinanciero
        #fields = '__all__'
        fields = ('id', 'monto', 'categoria_movimiento_financiero','comentario', 'fecha', 'cuenta')
"""
class MovimientoFinancieroForm(forms.Form):

    categoria_movimiento_financiero = forms.ModelChoiceField(queryset=CategoriaMovimientoFinanciero.objects.all())
    #tipo_categoria_movimiento_financiero = forms.ChoiceField(choices=get_tipos_categoria_movimiento_financiero_choices(), required=False)
    tipo_categoria_movimiento_financiero = forms.ChoiceField(choices=[], required=False)
    monto = forms.DecimalField()
    comentario = forms.CharField(max_length=1000, required=False)
    fecha = forms.DateField()
    cuenta = forms.ModelChoiceField(queryset=Cuenta.objects.all())

    #Iniciamos el form y le cargamos los choices al campo Tipo de Categoria Movimiento Financiero
    def __init__(self, *args, **kwargs):
        super(MovimientoFinancieroForm, self).__init__(*args, **kwargs)

        tipos = [(0, '--------')]

        for categoria in CategoriaMovimientoFinanciero.objects.all():
            tipos.append((categoria.id, "GASTO" if categoria.tipo_categoria_movimiento_financiero == 0 else "INGRESO"))

        self.fields['tipo_categoria_movimiento_financiero'].choices = tipos

class CuentaForm(forms.ModelForm):
    class Meta:
        model = Cuenta
        fields = ('id', 'nombre', 'moneda')

class CategoriaMovimientoFinancieroForm(forms.ModelForm):
    class Meta:
        model = CategoriaMovimientoFinanciero
        fields = ('id', 'nombre', 'tipo_categoria_movimiento_financiero')

templates/actualizarCategoriaMovimientoFinanciero.html
{% extends 'baseActualizarCrearCategoriaMovimientoFinanciero.html' %}

{% block titulo %} Actualizar categoría {% endblock titulo %}

{% block header1 %} Actualizar categoría {% endblock header1 %}

{% block label_boton_accion %} Guardar {% endblock label_boton_accion %}

templates/actualizarCuenta.html
{% extends 'baseActualizarCrearCuenta.html' %}

{% block titulo %} Actualizar cuenta {% endblock titulo %}

{% block header1 %} Actualizar cuenta {% endblock header1 %}

{% block label_boton_accion %} Guardar {% endblock label_boton_accion %}

templates/actualizarMovimientoFinanciero.html
{% extends 'baseActualizarCrearMovimientoFinanciero.html' %}

{% block titulo %} Actualizar movimiento {% endblock titulo %}

{% block header1 %} Actualizar movimiento {% endblock header1 %}

{% block label_boton_accion %} Guardar {% endblock label_boton_accion %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> {% block titulo %} {% endblock titulo %} </title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'listarMovimientosFinancieros' %}">ExpeNZes App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
          
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <!--li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li-->
                <!--li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-wrench" aria-hidden="true"></span>
                        Configuraciones
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'listarCuentas' %}">
                            <span class="fa fa-users" aria-hidden="true"></span>
                            Cuentas
                        </a>
                        <a class="dropdown-item" href="{% url 'listarCategoriasMovimientoFinanciero' %}">
                            <span class="fa fa-sitemap" aria-hidden="true"></span>
                            Categorias
                        </a>
                            <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <span class="fa fa-cog" aria-hidden="true"></span>
                            Avanzado
                        </a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled"> 
                        <span class="fa fa-user" aria-hidden="true"></span>
                        Usuario: {{ user.get_username }} 
                    </a>
                </li>
                <li class="nav=item">
                    <a class="nav-link"  href="{% url 'logout' %}"> 
                        <span class="fa fa-sign-out" aria-hidden="true"></span>
                        (Log out) 
                    </a>
                </li>
            </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                        <span class="fa fa-search" aria-hidden="true"></span>
                    </button>
                </form>
        </div>
    </nav>



    {% block cuerpo %} {% endblock cuerpo %}

</body>
</html>

templates/baseActualizarCrearCategoriaMovimientoFinanciero.html
{% extends 'base.html' %}

{% block cuerpo %}

    {% load widget_tweaks %}

    <h3> {% block header1 %} {% endblock header1 %} </h3>   

    <form method="post">
        {% csrf_token %}

        <div class="form-group form-inline ">
            {{ form.nombre.label }}
            {{ form.nombre|add_class:"form-control" }}
        </div>

        <div class="form-group form-inline ">
            Tipo:
            {{ form.tipo_categoria_movimiento_financiero|add_class:"form-control" }}
        </div>
    
        <button class="btn btn-success" type="submit"> 
            {% block label_boton_accion %} {% endblock label_boton_accion %} 
            <span class="fa fa-save" aria-hidden="true"></span>
        </button>
        <a class="btn btn-light" href="{% url 'listarCategoriasMovimientoFinanciero' %}"> 
            Volver
            <span class="fa fa-reply" aria-hidden="true"></span>
         </a>

    </form>

{% endblock cuerpo %}

templates/baseActualizarCrearMovimientoFinanciero.html
{% extends 'base.html' %}

{% block cuerpo %}

    {% load widget_tweaks %}

    <h3> {% block header1 %} {% endblock header1 %} </h3>   

    <script>

        function actualizarColorYTextoTipoCategoriaMovimientoFinanciero(){

            $("#id_tipo_categoria_movimiento_financiero").val( $("#id_categoria_movimiento_financiero").val() )

            if ( $("#id_tipo_categoria_movimiento_financiero option:selected").text() == "GASTO" )
            {
                $("#id_tipo_categoria_movimiento_financiero").removeClass("bg-success").addClass('bg-danger text-white');

            } else if ( $("#id_tipo_categoria_movimiento_financiero option:selected").text() == "INGRESO" ) 
            
            {

                $("#id_tipo_categoria_movimiento_financiero").removeClass("bg-danger").addClass('bg-success text-white');

            }

            else 
            {
                $("#id_tipo_categoria_movimiento_financiero").removeClass("bg-danger bg-success text-white");
            }

        }

        $(document).ready(function(){

            actualizarColorYTextoTipoCategoriaMovimientoFinanciero()

            $("#id_categoria_movimiento_financiero").change(function(){

                actualizarColorYTextoTipoCategoriaMovimientoFinanciero()
            })
        }) 
    </script>

    <form method="post">
        {% csrf_token %}

        <div class="form-group form-inline ">
            <label for="">Categoría:</label>
            {{ form.categoria_movimiento_financiero|add_class:"form-control" }}
        </div>

        <div class="form-group form-inline ">
            <label for="">Tipo:</label>
            {{ form.tipo_categoria_movimiento_financiero|add_class:"form-control"|attr:"disabled" }}
        </div>

        <div class="form-group form-inline ">
            {{ form.monto.label }}
            {{ form.monto|add_class:"form-control" }}
        </div>

        <div class="form-group form-inline ">
            {{ form.cuenta.label }} 
            {{ form.cuenta|add_class:"form-control" }}
        </div>

        <div class="form-group form-inline ">
            {{ form.fecha.label }} 
            {{ form.fecha|add_class:"form-control"|attr:"type:date" }}
        </div>


        <div class="form-group form-inline ">
            {{ form.comentario.label }} 
            {{ form.comentario|add_class:"form-control"}}
        </div>
    
        <button class="btn btn-success" type="submit"> 
            {% block label_boton_accion %} {% endblock label_boton_accion %} 
            <span class="fa fa-save" aria-hidden="true"></span>
        </button>
        <a class="btn btn-light" href="{% url 'listarMovimientosFinancieros' %}"> 
            Volver
            <span class="fa fa-reply" aria-hidden="true"></span>
         </a>

    

    </form>

{% endblock cuerpo %}

templates/confirmarEliminarCategoriaMovimientoFinanciero.html
{% extends 'base.html' %}
{% block titulo %} Eliminar categoria {% endblock titulo %}
{% block cuerpo %}


{% if mensaje %}

<div class="alert alert-danger" role="alert"> {{ mensaje }} </div>

{% else %}
<form method="post">

    {% csrf_token %}

    <h1> Está seguro que desea eliminar la categoria? </h1>

<button class="btn btn-danger" type="submit"> Confirmar </button>

{% endif %}

<a class="btn btn-light" href="{% url 'listarCategoriasMovimientoFinanciero' %}"> Volver </a>

</form>
{% endblock cuerpo %}

templates/confirmarEliminarCuenta.html
{% extends 'base.html' %}
{% block titulo %} Eliminar cuenta {% endblock titulo %}
{% block cuerpo %}


{% if mensaje %}

<div class="alert alert-danger" role="alert"> {{ mensaje }} </div>

{% else %}
<form method="post">

    {% csrf_token %}

    <h1> Está seguro que desea eliminar la cuenta? </h1>

<button class="btn btn-danger" type="submit"> Confirmar </button>

{% endif %}

<a class="btn btn-light" href="{% url 'listarCuentas' %}"> Volver </a>

</form>
{% endblock cuerpo %}

templates/crearCategoriaMovimientoFinanciero.html
{% extends 'baseActualizarCrearCategoriaMovimientoFinanciero.html' %}

{% block titulo %} Nueva categoría {% endblock titulo %}

{% block header1 %} Crear categoría {% endblock header1 %}

{% block label_boton_accion %} Crear {% endblock label_boton_accion %}

templates/crearMovimientoFinanciero.html
{% extends 'baseActualizarCrearMovimientoFinanciero.html' %}

{% block titulo %} Nuevo movimiento {% endblock titulo %}

{% block header1 %} Crear movimiento {% endblock header1 %}

{% block label_boton_accion %} Crear {% endblock label_boton_accion %}

templates/indexLoginError.html
{% extends 'indexLogin.html' %}
{% block mensaje %} 
    <div class="alert alert-danger" role="alert">
        Usuario o contraseña incorrectos 
    </div>
{% endblock mensaje %}

templates/listarCategoriasMovimientoFinanciero.html
{% extends 'base.html' %}
{% block titulo %} Lista de Categorias {% endblock titulo %}
{% block cuerpo %}

<p>
    <h3> Categorias </h3>
    <a class="btn btn-dark" href="{% url 'crearCategoriaMovimientoFinanciero' %}"> 
        Crear 
        <span class="fa fa-plus" aria-hidden="true"></span>
    </a>
</p>

<table class="table table-bordered table-sm table-hover">
    <thead class="table-dark">
        <tr>
            <th>Nombre</th>
            <th>Tipo</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% for categoria in object_list %}
        <tr>
            <td> {{ categoria.nombre }} </td>
            <td> {% if categoria.tipo_categoria_movimiento_financiero == 0 %} GASTO {% else %} INGRESO {% endif %}</td>
            <td> 
                <a class="btn btn-primary" href="{% url 'actualizarCategoriaMovimientoFinanciero' categoria.id %}"> 
                    <span class="fa fa-edit" aria-hidden="true"></span>
                </a>
            </td>
            <td> 
                <a class="btn btn-danger" href="{% url 'eliminarCategoriaMovimientoFinanciero' categoria.id %}">
                    <span class="fa fa-trash" aria-hidden="true"></span>
                </a> 
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a class="btn btn-light" href="{% url 'listarMovimientosFinancieros' %}"> Volver </a>

{% endblock cuerpo %}

templates/listarCuentas.html
{% extends 'base.html' %}
{% block titulo %} Lista de Cuentas {% endblock titulo %}
{% block cuerpo %}

<p>
    <h3> Cuentas </h3>
    <a class="btn btn-dark" href="{% url 'crearCuenta' %}"> 
        Crear 
        <span class="fa fa-plus" aria-hidden="true"></span>
    </a>
</p>

<table class="table table-bordered table-sm table-hover">
    <thead class="table-dark">
        <tr>
            <th>Nombre</th>
            <th>Moneda</th>
            <th>Saldo</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% for cuenta in object_list %}
        <tr>
            <td> {{ cuenta.nombre }} </td>
            <td> {{ cuenta.moneda }} </td>
            <td> {{ cuenta.saldo }} </td>
            <td> 
                <a class="btn btn-primary" href="{% url 'actualizarCuenta' cuenta.id %}"> 
                    <span class="fa fa-edit" aria-hidden="true"></span>
                </a>
            </td>
            <td> 
                <a class="btn btn-danger" href="{% url 'eliminarCuenta' cuenta.id %}">
                    <span class="fa fa-trash" aria-hidden="true"></span>
                </a> 
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<a class="btn btn-light" href="{% url 'listarMovimientosFinancieros' %}"> Volver </a>

{% endblock cuerpo %}

templates/listarMovimientosFinancieros.html
{% extends 'base.html' %}
{% block titulo %} Lista de Movimientos {% endblock titulo %}
{% block cuerpo %}

<p>
    <h3> Movimientos </h3>
    <a class="btn btn-dark" href="{% url 'crearMovimientoFinanciero' %}"> 
        Crear 
        <span class="fa fa-plus" aria-hidden="true"></span>
    </a>
</p>

<table class="table table-bordered table-sm table-hover">
    <thead class="table-dark" >
        <tr>
            <th>Cuenta</th>
            <th>Moneda</th>
            <th>Saldo</th>
        </tr>
    </thead>
    <tbody>
        {% for cuenta in cuentas %}
        <tr>
            <td> {{ cuenta.nombre }} </td>
            <td> {{ cuenta.moneda }} </td>
            <td> {{ cuenta.saldo }} </td>
        </tr>
        {% endfor %}
    </tbody>
</table>



<table class="table table-bordered table-sm table-hover">
    <thead class="table-dark">
        <tr>
            <th>Fecha</th>
            <th>Categoria</th>
            <th>Monto</th>
            <th>Cuenta</th>
            <th>Comentario</th>
            <th>id</th>
            <th>Editar</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% for movimiento_financiero in movimientos_financieros %}
        <tr>
            <td> {{ movimiento_financiero.fecha|date:'d/m/Y' }} </td>
            <td> {{ movimiento_financiero.categoria_movimiento_financiero }} </td>
            <td> {{ movimiento_financiero.monto }} </td>
            <td> {{ movimiento_financiero.cuenta }} </td>
            <td>
                {% if movimiento_financiero.comentario %}
                {{ movimiento_financiero.comentario }}
                {% else %}
                &nbsp;
                {% endif %}
            </td>
            <td> {{ movimiento_financiero.id }} </td>
            <td> 
                <a class="btn btn-primary" href="{% url 'actualizarMovimientoFinanciero' movimiento_financiero.id %}"> 
                    <span class="fa fa-edit" aria-hidden="true"></span>
                </a>
            </td>
            <td> 
                <a class="btn btn-danger" href="{% url 'eliminarMovimientoFinanciero' movimiento_financiero.id %}">
                    <span class="fa fa-trash" aria-hidden="true"></span>
                </a> 
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock cuerpo %}